import './globals.css';
import type { Metadata } from 'next';
import { Karla } from 'next/font/google';

const karla = Karla({
  subsets: ['latin-ext'],
  variable: '--font-karla',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${karla.className} w-screen h-screen`}>{children}</body>
    </html>
  );
}
