import type { Metadata } from "next";
import { Karla } from "next/font/google";
import { Home } from "react-feather";
import "./globals.css";
import Link from "next/link";

const karla = Karla({
  subsets: ["latin-ext"],
  variable: "--font-karla",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${karla.className} w-screen h-screen bg-gray-900 text-gray-400`}
      >
        {children}
        <HomeLink />
      </body>
    </html>
  );
}

const HomeLink = () => (
  <Link
    href="/"
    className="top-[10px] right-2 absolute flex place-items-center gap-2 bg-gray-800 hover:bg-gray-700 px-2 py-1 rounded-md text-gray-200 text-sm"
  >
    <Home className="w-4 h-4" />
  </Link>
);
