import type { Metadata } from 'next';
import { Karla } from 'next/font/google';
import { Home } from 'react-feather';
import './globals.css';
import Link from 'next/link';

const karla = Karla({
  subsets: ['latin-ext'],
  variable: '--font-karla',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${karla.className} w-screen h-screen bg-gray-900 text-gray-400`}
      >
        {children}
        <HomeLink />
      </body>
    </html>
  );
}

const HomeLink = () => (
  <Link
    href='/'
    className='text-gray-200 absolute top-[10px] right-2 flex gap-2 text-sm place-items-center
    bg-gray-800 rounded-md px-2 py-1 hover:bg-gray-700'
  >
    <Home className='h-4 w-4' />
  </Link>
);
